name: Sync LeetCode to GitHub

on:
  workflow_dispatch:      # Allows you to click a button to sync
  schedule:
    - cron: '0 8 * * *'   # Runs automatically every day at 8:00 AM

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Sync Code
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: solutions
          filename-format: "leetcode" # Names files like '1-two-sum.py'
